import { Geist, Geist_Mono, Albert_Sans, Aldrich, Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const albertSans = Albert_Sans({
  variable: "--font-albert-sans",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const aldrich = Aldrich({
  variable: "--font-aldrich",
  subsets: ["latin"],
  weight: ["400"],
});

const productSans = localFont({
  variable: "--font-product-sans",
  src: [
    {
      path: "../fonts/PTSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/PTSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/PTSans-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/PTSans-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
  ]
})

export const metadata = {
  title: "GDG Kolkata 2025",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${albertSans.variable} ${aldrich.variable} ${openSans.variable} ${productSans.variable} antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
        <Toaster position="top-center"/>
      </body>
    </html>
  );
}
